sudo: required
services: 
  - docker
  
before_install:
  - docker build -t francescacarminati/docker-react -f Dockerfile.dev .

script:
  - docker run francescacarminati/docker-react npm run test -- --coverage